# BUILDER
FROM bde2020/spark-base:3.2.1-hadoop3.2 AS builder

RUN apk add --no-cache \
    build-base \
    gcc \
    g++ \
    gfortran \
    musl-dev \
    linux-headers \
    python3-dev \
    openblas-dev \
    cmake \
    pkgconfig \
    curl

COPY --from=ghcr.io/astral-sh/uv:0.5.16 /uv /usr/local/bin/uv

ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk

WORKDIR /app
COPY . .
RUN uv sync --extra dq


# MAIN

FROM bde2020/spark-base:3.2.1-hadoop3.2

RUN apk add --no-cache bash curl nano libgfortran openblas

ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
WORKDIR /app
COPY --from=builder /app /app

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV PYSPARK_PYTHON=/app/.venv/bin/python
ENV PYSPARK_DRIVER_PYTHON=/app/.venv/bin/python

CMD ["tail", "-f", "/dev/null"]