version: "1.0.0"

run_date:
  start_date: "${START_DATE}"
  end_date: "${END_DATE}"

# =====================================================
# PIPELINE
# =====================================================
pipeline:
  name: sales_delta_pipeline
  source_type: mongo
  catalog_type: nessie
  stages:
    - bronze
    - silver
    - gold
  tablenames:
    - passengers
    - trains
    - stations
    - routes
    - tickets

# =====================================================
# SOURCES
# =====================================================
sources:
  mongo:
    username: "${MONGO_USERNAME}"
    password: "${MONGO_PASSWORD}"
    host: "${MONGO_HOSTNAME}"
    port: "${MONGO_PORT}"
    uri: "${MONGO_URL}"
    database: "${MONGO_DATABASE}"

# =====================================================
# CATALOGS
# =====================================================
catalogs:
  nessie:
    name: nessie
    host: "${NESSIE_HOSTNAME}"
    port: "${NESSIE_PORT}"
    uri: "${NESSIE_URL}"
    ref: "${NESSIE_REF}"
    warehouse: "${WAREHOUSE_LOCATION_DEV}"

# =====================================================
# STORAGES
# =====================================================
storages:
  hdfs:
    uri: "${HADOOP_URL}"
    host: "${HADOOP_HOSTNAME}"
    port: "${HADOOP_PORT}"

# =====================================================
# SPARK CONFIGURATION
# =====================================================
spark:
  master: "${SPARK_MASTER}"

  common_config: &spark_common
    spark.driver.bindAddress: "0.0.0.0"
    spark.driver.host: "spark-submit"
    spark.driver.port: 4040

    spark.driver.memory: "1g"
    spark.executor.memory: "512m"
    spark.executor.cores: 2
    spark.executor.instances: 4

    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.jars.packages: org.mongodb:mongodb-driver-sync:4.11.1,org.mongodb.spark:mongo-spark-connector_2.12:10.5.0,org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:1.4.3,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.2_2.12:0.67.0
    spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
    
    spark.sql.catalog.nessie: org.apache.iceberg.spark.SparkCatalog
    spark.sql.catalog.nessie.catalog-impl: org.apache.iceberg.nessie.NessieCatalog
    spark.sql.catalog.nessie.uri: "${NESSIE_URL}"
    spark.sql.catalog.nessie.ref: "${NESSIE_REF}"

    spark.mongodb.read.connection.uri: "${MONGO_URL}"
    spark.mongodb.write.connection.uri: "${MONGO_URL}"
    spark.mongodb.read.partitioner: com.mongodb.spark.sql.connector.read.partitioner.PaginateIntoPartitionsPartitioner
    spark.mongodb.read.partitionerOptions.numberOfPartitions: 10

    spark.sql.catalog.nessie.warehouse: "${WAREHOUSE_LOCATION_DEV}"
    spark.sql.sources.partitionOverwriteMode: dynamic

  dev:
    app_name: "Development"
    config:
      <<: *spark_common
      spark.sql.shuffle.partitions: 16

  bronze:
    app_name: "Bronze_Pipeline"
    config:
      <<: *spark_common
      spark.sql.shuffle.partitions: 16

  silver:
    app_name: "Silver_Pipeline"
    config:
      <<: *spark_common
      spark.sql.shuffle.partitions: 8
      spark.sql.adaptive.enabled: true

  gold:
    app_name: "Gold_Pipeline"
    config:
      <<: *spark_common
      spark.sql.shuffle.partitions: 8
      spark.sql.adaptive.enabled: true

# =====================================================
# SCHEMAS / NAMESPACES
# =====================================================
schemas:
  source:
    name: source
    description: Raw data
    owner: data_engineering_team
    upstream: source
    downstream: bronze
    retention_days: 30

  bronze:
    name: bronze
    description: Raw ingested data from sources
    owner: data_engineering_team
    upstream: source
    downstream: silver
    retention_days: 30

  silver:
    name: silver
    description: Cleaned and conformed data
    owner: data_engineering_team
    upstream: bronze
    downstream: gold
    retention_days: 180
    
  gold:
    name: gold
    description: Analytics-ready data for BI and ML
    owner: analytics_team
    upstream: silver
    downstream: gold
    retention_days: 365

# =====================================================
# TABLES
# =====================================================

tables:
  passengers:
    type: scd2
    partitioned_by: updated_at
    write_mode:
      bronze: overwrite_partitions
      silver: custom
      gold: custom
    schema:
      source: |
        _id INT,
        name STRING,
        gender STRING,
        phone STRING,
        email STRING,
        created_at STRING,
        updated_at STRING

      bronze: |
        id INT,
        name STRING,
        gender STRING,
        phone STRING,
        email STRING,
        created_at TIMESTAMP,
        updated_at TIMESTAMP

      silver: |
        sk_id BIGINT,
        id INT,
        name STRING,
        gender STRING,
        phone STRING,
        email STRING,
        is_active BOOLEAN,
        start_date TIMESTAMP,
        end_date TIMESTAMP

    query:
      - |  
        MERGE INTO {full_table_name} t
        USING {table_view} s
        ON t.id = s.id AND t.is_active = true

        WHEN MATCHED AND (
          t.name <> s.name OR 
          t.gender <> s.gender OR 
          t.phone <> s.phone OR 
          t.email <> s.email
        )
        THEN UPDATE SET 
          t.is_active = false,
          t.end_date = s.updated_at

        WHEN NOT MATCHED THEN 
        INSERT (sk_id, id, name, gender, phone, email, is_active, start_date, end_date)
        VALUES(s.sk_id, s.id, s.name, s.gender, s.phone, s.email, true, s.updated_at, null)

      - |
        WITH CURRENT_RECORD AS (
            SELECT 
                id
            FROM {full_table_name}
            WHERE is_active = true
        )
        INSERT INTO {full_table_name}
        SELECT 
            pc.sk_id,
            pc.id,
            pc.name,
            pc.gender,
            pc.phone,
            pc.email,
            true as is_active,
            pc.updated_at as start_date,
            NULL as end_date 
        FROM {table_view} pc 
        LEFT ANTI JOIN 
            CURRENT_RECORD cr ON pc.id = cr.id 

  stations:
    type: scd1
    partitioned_by: updated_at
    write_mode:
      bronze: overwrite_partitions
      silver: custom
      gold: custom
    schema: 
      source: |
        _id INT,
        name STRING,
        city STRING,
        code STRING,
        updated_at STRING,
        created_at STRING

      bronze: |
        id INT,
        name STRING,
        city STRING,
        code STRING,
        updated_at TIMESTAMP,
        created_at TIMESTAMP

      silver: |
        sk_id BIGINT,
        id INT,
        name STRING,
        city STRING,
        code STRING,
        is_deleted BOOLEAN
    
    query:
      - |
        MERGE INTO {full_table_name} t
        USING {table_view} s
        ON t.id = s.id

        WHEN MATCHED AND (
            t.name <> s.name OR
            t.city <> s.city OR
            t.code <> s.code OR
            t.is_deleted = true
        )
        THEN UPDATE SET
            t.name = s.name,
            t.city = s.city,
            t.code = s.code,
            t.is_deleted = false

        WHEN NOT MATCHED THEN
        INSERT (
            sk_id,
            id,
            name,
            city,
            code,
            is_deleted
        )
        VALUES (
            s.sk_id,
            s.id,
            s.name,
            s.city,
            s.code,
            false
        )

      - |
        UPDATE {full_table_name} t
        SET is_deleted = true
        WHERE NOT EXISTS (
            SELECT 1
            FROM {table_view} s
            WHERE s.id = t.id
        )

  trains:
    type: scd2
    partitioned_by: updated_at
    write_mode:
      bronze: overwrite_partitions
      silver: custom
      gold: custom
    schema: 
      source: |
        _id INT,
        name STRING,
        type STRING,
        capacity INT,
        created_at STRING,
        updated_at STRING

      bronze: |
        id INT,
        name STRING,
        type STRING,
        capacity INT,
        created_at TIMESTAMP,
        updated_at TIMESTAMP

      silver: |
        sk_id BIGINT,
        id INT,
        name STRING,
        type STRING,
        capacity INT,
        is_active BOOLEAN,
        start_date TIMESTAMP,
        end_date TIMESTAMP
    
    query: 
      - |
        MERGE INTO {full_table_name} t
        USING {table_view} s
        ON t.id = s.id AND t.is_active = true

        WHEN MATCHED AND (
            t.name <> s.name OR 
            t.type <> s.type OR 
            t.capacity <> s.capacity
        )
        THEN UPDATE SET 
            t.is_active = false,
            t.end_date = s.updated_at

        WHEN NOT MATCHED THEN 
        INSERT (sk_id, id, name, type, capacity, is_active, start_date, end_date)
        VALUES(s.sk_id, s.id, s.name, s.type, s.capacity, true, s.updated_at, null)
      
      - |
        WITH CURRENT_RECORD AS (
            SELECT 
                id
            FROM {full_table_name}
            WHERE is_active = true
        )

        INSERT INTO {full_table_name}
        SELECT
            sc.sk_id,
            sc.id,
            sc.name,
            sc.type,
            sc.capacity,
            true as is_active,
            sc.updated_at as start_date,
            NULL as end_date
        FROM {table_view} sc 
        LEFT ANTI JOIN CURRENT_RECORD cr 
        ON sc.id = cr.id
   
  routes:
    type: scd1
    partitioned_by: updated_at
    write_mode:
      bronze: overwrite_partitions
      silver: custom
      gold: custom
    schema: 
      source: |
        _id INT,
        origin STRING,
        destination STRING,
        train_id INT,
        distance_km INT,
        duration_minutes INT,
        updated_at STRING,
        created_at STRING

      bronze: |
        id INT,
        origin STRING,
        destination STRING,
        train_id INT,
        distance_km INT,
        duration_minutes INT,
        updated_at TIMESTAMP,
        created_at TIMESTAMP
      
      silver: |
        sk_id BIGINT,
        id INT,
        org_station_id INT,
        dest_station_id INT,
        train_id INT,
        distance_km INT,
        duration_minutes INT,
        is_deleted BOOLEAN
    
    query: 
      - |      
        MERGE INTO {full_table_name} t
        USING {table_view} s
        ON t.id = s.id

        WHEN MATCHED AND (
            t.sk_org_station_id <> s.sk_org_station_id OR 
            t.sk_dest_station_id <> s.sk_dest_station_id OR 
            t.sk_train_id <> s.sk_train_id OR 
            t.distance_km <> s.distance_km OR 
            t.duration_minutes <> s.duration_minutes OR
            t.is_deleted = true
        )
        THEN UPDATE SET 
            sk_org_station_id = s.sk_org_station_id,
            sk_dest_station_id = s.sk_dest_station_id,
            sk_train_id = s.sk_train_id,
            distance_km = s.distance_km,
            duration_minutes = s.duration_minutes,
            is_deleted = false

        WHEN NOT MATCHED THEN 
        INSERT (
          sk_id, 
          id, 
          sk_org_station_id, 
          sk_dest_station_id, 
          sk_train_id, 
          distance_km, 
          duration_minutes, 
          is_deleted
        )
        
        VALUES(
          s.sk_id, 
          s.id, 
          s.sk_org_station_id, 
          s.sk_dest_station_id, 
          s.sk_train_id, 
          s.distance_km, 
          s.duration_minutes, 
          false
        )

      - |
        UPDATE {full_table_name} r
        SET is_deleted = true
        WHERE NOT EXISTS (
            SELECT 1
            FROM {table_view} s
            WHERE s.id = r.id
        )

    depends_on:
      stations:
        catalog: nessie
        schema: silver
      trains:
        catalog: nessie
        schema: silver

  tickets:
    type: fact
    partitioned_by: created_at
    write_mode:
      bronze: overwrite_partitions
      silver: custom
      gold: custom
    schema: 
      source: |
        _id INT,
        ticket_id STRING,
        route_id INT,
        passenger_id INT,
        train_id INT,
        discount DECIMAL(10, 2),
        price DECIMAL(38, 2),
        class STRING,
        seat_number STRING,
        status STRING,
        departure_date STRING,
        extra_info STRUCT<
          child_discount: BOOLEAN,
          family_members: INT,
          promo_code: STRING,
          source: STRING
        >,
        payment STRUCT<
          method: STRING,
          bank: STRING,
          provider: STRING
        >,
        addons ARRAY<STRING>,
        created_at STRING

      bronze: |
        id INT,
        ticket_id STRING,
        route_id INT,
        passenger_id INT,
        train_id INT,
        discount DECIMAL(10, 2),
        price DECIMAL(38, 2),
        class STRING,
        seat_number STRING,
        status STRING,
        departure_date TIMESTAMP,
        extra_info STRUCT<
          child_discount: BOOLEAN,
          family_members: INT,
          promo_code: STRING,
          source: STRING
        >,
        payment STRUCT<
          method: STRING,
          bank: STRING,
          provider: STRING
        >,
        addons ARRAY<STRING>,
        created_at TIMESTAMP

      silver: |
        ticket_id         STRING,
        route_sk_id       BIGINT,
        passenger_sk_id   BIGINT,
        train_sk_id       BIGINT,
        class_id          INT,
        payment_id        INT,
        active_status_id  INT,
        day_of_week       TINYINT,
        booking_lead_days INT,
        departure_date    TIMESTAMP,
        paid_at           TIMESTAMP,
        cancelled_at      TIMESTAMP,
        refunded_at       TIMESTAMP,
        created_at        TIMESTAMP,
        price             DECIMAL(18, 2),
        discount          DECIMAL(18, 2),
        final_price       DECIMAL(18, 2),
        family_flag       BOOLEAN,
        has_child         BOOLEAN,
        has_promo         BOOLEAN,
        is_weekend        BOOLEAN
  
    query: 
      - |
        INSERT OVERWRITE TABLE {full_table_name}
        SELECT *
        FROM {table_view}


    depends_on:
      stations:
        catalog: nessie
        schema: silver
      routes:
        catalog: nessie
        schema: silver
      trains:
        catalog: nessie
        schema: silver
      passengers:
        catalog: nessie
        schema: silver
      class:
        catalog: nessie
        schema: silver
      status:
        catalog: nessie
        schema: silver
      payment:
        catalog: nessie
        schema: silver

# =====================================================
# PUSHDOWN FILTERS
# =====================================================
filters:
  bronze:
    type: mongo
    tables:
      tickets:
        field: created_at
      passengers:
        field: updated_at
      routes:
        field: updated_at
      trains:
        field: updated_at
      stations:
        field: updated_at
        
  silver:
    type: iceberg
    tables:
      tickets:
        field: created_at
      passengers:
        field: updated_at
      routes:
        field: updated_at
      trains:
        field: updated_at
      stations:
        field: updated_at

      
      

            





    